sudo: false

language: node_js
node_js: "12.16.2"

cache:
  directories:
#    - node_modules
#    - app/node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
#    - $HOME/.npm/_prebuilds

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

jobs:
  include:
    - stage: Test
      script:
        - npm test
    - stage: Deploy Linux
      #if: tag IS present
      os: linux
      dist: trusty
      script:
        - npm run build -- --linux -p always
    - stage: Deploy Mac and Windows
      #if: tag IS present
      os: osx
      osx_image: xcode10.1
      script:
        - npm run build -- --mac -p always
        - npm run build -- --win -p always
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine
